spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    url: jdbc:mysql://localhost:3306/onion_market
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
file:
  dir: C:/fileUploadExample/uploadfile/
image:
  upload-dir: C:/Users/pokly/Documents/NBK/news-feed/src/main/resources/images
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

---

spring:

  config:
    activate:
      on-profile: test

  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: h2

  h2:
    console:
      enabled: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


